// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiQrRMaVUUdej94QcIoEgj1K0sE-2iwYs',
    appId: '1:55780821656:web:9ec6014204020d906adeed',
    messagingSenderId: '55780821656',
    projectId: 'linkyoutask',
    authDomain: 'linkyoutask.firebaseapp.com',
    storageBucket: 'linkyoutask.appspot.com',
    measurementId: 'G-S2Q6CMCHDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC49JZY1ezTlkSRQne4pBghvA_DxFkHyG8',
    appId: '1:55780821656:android:92083892652ad8066adeed',
    messagingSenderId: '55780821656',
    projectId: 'linkyoutask',
    storageBucket: 'linkyoutask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc2fIAspVF2CjOsC5zD8RH01zFZqqdBN0',
    appId: '1:55780821656:ios:077452c4044170316adeed',
    messagingSenderId: '55780821656',
    projectId: 'linkyoutask',
    storageBucket: 'linkyoutask.appspot.com',
    iosClientId: '55780821656-fgtqt8fhlig76daunhac9b2tg9on6lhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkyoutask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc2fIAspVF2CjOsC5zD8RH01zFZqqdBN0',
    appId: '1:55780821656:ios:b733fb4e36c01bd76adeed',
    messagingSenderId: '55780821656',
    projectId: 'linkyoutask',
    storageBucket: 'linkyoutask.appspot.com',
    iosClientId: '55780821656-5h8lb5uu4kr1815f4ml5mh3htije4to0.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkyoutask.RunnerTests',
  );
}
